name: deploy_to_firebase_hosting

on:
  push:
    branches: [main]

jobs:
  deploy_to_firebase_hosting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: install dependencies
        run: HUSKY=0&& npm i

      - name: make build for stating
        run: npm run build:staging

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:web
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
